cisco_serialnumberinformation/urls.py
# myapp/urls.py
from django.urls import path
from .views import get_sni

urlpatterns = [
    path('', get_sni, name='get_sni'),
]

hide1_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
from django.conf.urls import handler500, handler404
from django.shortcuts import render
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('tools-pm/', include('parser_app.urls')),
    path('tools-json/', include('json_editor.urls')),
    path('topology-drawer/', include('topology_drawer.urls')),
    path('tools-cisco/end-of-support/', include('cisco_endofsupport.urls')),
    path('tools-cisco/serial-number-information/', include('cisco_serialnumberinformation.urls')),
    path('tools-cisco/software-suggestions/', include('cisco_softwaresuggestions.urls')),
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('activity-log/', include('activity_log.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

def custom_error_500(request):
    return render(request, '500.html', status=500)

handler500 = custom_error_500

def custom_error_404(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_error_404

parser_app/urls.py
from django.urls import path
from .views import upload_file, download_json

urlpatterns = [
    path("", upload_file, name="upload_file"),
    path('download-json/', download_json, name='download_as_json'),
]

cisco_serialnumberinformation/models.py
from django.db import models

# Create your models here.

cisco_serialnumberinformation/forms.py
# myapp/forms.py
from django import forms

class SerialNumberForm(forms.Form):
    serial_number = forms.CharField(label='Serial Number', max_length=100)

cisco_serialnumberinformation/views.py
# myapp/views.py
from django.shortcuts import render
from .forms import SerialNumberForm
from .sni import get_apikey, get_sni_data

def get_sni(request):
    api_key = None
    sni_data = None
    error_message_apikey = None
    error_message_sni_data = None

    if request.method == 'POST':
        form = SerialNumberForm(request.POST)
        if form.is_valid():
            serial_number = form.cleaned_data['serial_number']

            # Call your existing functions to get API key and EOX data
            api_key, error_message_apikey = get_apikey()
            if api_key:
                sni_data, error_message_sni_data = get_sni_data(api_key, serial_number)

    else:
        form = SerialNumberForm()

    return render(request, 'get_sni.html', {'form': form, 'api_key': api_key, 'sni_data': sni_data,
                                            'error_message_apikey': error_message_apikey,
                                            'error_message_sni_data': error_message_sni_data})

cisco_serialnumberinformation/templates/get_sni.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="row">
    <div class="col-lg-12 mx-auto">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <a class="h3 d-block mt-3 text-decoration-none text-dark">Get Serial Number Information Data</a>
            </div>
            <div class="card-body form-group">
                <form method="post" action="{% url 'get_sni' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_serial_number" class="form-label">Serial Number</label>
                        <input type="text" name="serial_number" class="form-control" id="id_serial_number"
                            placeholder="Enter Serial Number" maxlength="100">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger" id="submit" name="submit">
                            <span class="icon-send"></span> Submit
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% if sni_data %}
        <div class="card shadow border-radius-lg mt-4">
            <div class="card-body">
                <h5 class="text-center mb-3">Serial Number Information Data</h5>
                <div class="table-responsive">
                    <table class="table align-items-center mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>Serial Number</th>
                                <th>Base PID</th>
                                <th>Is Covered</th>
                                <th>Covered End Date</th>
                                <th>Service Level</th>
                                <th>Customer Name</th>
                                <th>Warranty Type</th>
                                <th>Warranty End Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sn in sni_data.serial_numbers %}
                            <tr>
                                <td>{{ sn.sr_no }}</td>
                                <td>
                                    {% for base_pid in sn.base_pid_list %}
                                    {{ base_pid.base_pid }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{ sn.is_covered }}</td>
                                <td>{{ sn.covered_product_line_end_date }}</td>
                                <td>{{ sn.service_line_descr }}</td>
                                <td>{{ sn.contract_site_customer_name }}</td>
                                <td>{{ sn.warranty_type }}</td>
                                <td>{{ sn.warranty_end_date }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}