cisco_endofsupport/urls.py
# myapp/urls.py
from django.urls import path
from .views import get_eox

urlpatterns = [
    path('', get_eox, name='get_eox'),
]

hide1_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
from django.conf.urls import handler500, handler404
from django.shortcuts import render
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('tools-pm/', include('parser_app.urls')),
    path('tools-json/', include('json_editor.urls')),
    path('topology-drawer/', include('topology_drawer.urls')),
    path('tools-cisco/end-of-support/', include('cisco_endofsupport.urls')),
    path('tools-cisco/serial-number-information/', include('cisco_serialnumberinformation.urls')),
    path('tools-cisco/software-suggestions/', include('cisco_softwaresuggestions.urls')),
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('activity-log/', include('activity_log.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

def custom_error_500(request):
    return render(request, '500.html', status=500)

handler500 = custom_error_500

def custom_error_404(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_error_404

parser_app/urls.py
from django.urls import path
from .views import upload_file, download_json

urlpatterns = [
    path("", upload_file, name="upload_file"),
    path('download-json/', download_json, name='download_as_json'),
]

cisco_endofsupport/models.py
from django.db import models

# Create your models here.

cisco_endofsupport/forms.py
# myapp/forms.py
from django import forms

# class SerialNumberForm(forms.Form):
#     serial_number = forms.CharField(label='Serial Number', max_length=100)
#     product_id = forms.CharField(label='Product ID', max_length=100)

class SerialNumberForm(forms.Form):
    SEARCH_CHOICES = [
        ('serial_number', 'Search by Serial Number'),
        ('product_id', 'Search by Product ID'),
    ]

    search_type = forms.ChoiceField(
        label='Search Type',
        choices=SEARCH_CHOICES,
        widget=forms.Select(),
    )

    search_value = forms.CharField(label='Search Value')

cisco_endofsupport/views.py
# myapp/views.py
from django.shortcuts import render
from .forms import SerialNumberForm
from .eox import get_apikey, get_eox_data, get_eox_data_2

def get_eox(request):
    api_key = None
    eox_data = None
    error_message_apikey = None
    error_message_eox_data = None

    if request.method == 'POST':
        form = SerialNumberForm(request.POST)
        if form.is_valid():
            search_type = form.cleaned_data['search_type']
            query_value = form.cleaned_data['search_value']
            api_key, error_message_apikey = get_apikey()
            if api_key:
                if search_type == 'serial_number':
                    eox_data, error_message_eox_data = get_eox_data(api_key, query_value)
                elif search_type == 'product_id':
                    eox_data, error_message_eox_data = get_eox_data_2(api_key, query_value)
    else:
        form = SerialNumberForm()

    return render(request, 'get_eox.html', {'form': form, 'api_key': api_key, 'eox_data': eox_data,
                                            'error_message_apikey': error_message_apikey,
                                            'error_message_eox_data': error_message_eox_data})

cisco_endofsupport/templates/get_eox.html
{% extends 'base.html' %}

{% block content %}
{% load widget_tweaks %}
<div class="row">
    <div class="col-lg-12 mx-auto">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <a class="h3 d-block mt-3 text-decoration-none text-dark">Get End Of Support Data</a>
            </div>
            <div class="card-body form-group">
                <form method="post" action="{% url 'get_eox' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="id_search_type">Search Type</label>
                        {{ form.search_type|add_class:"form-select" }}
            
                        <label class="form-label mt-3" for="id_search_value">Search Value</label>
                        {{ form.search_value|add_class:"form-control" }}
                    </div>
            
                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-danger" id="submit" name="submit">
                            <span class="icon-send"></span> Submit
                        </button>
                    </div>
                </form>
            </div>
        </div>

        {% if error_message_apikey or error_message_eox_data or eox_data %}
        <div class="card shadow border-radius-lg mt-4">
            <div class="card-body">
                {% if error_message_apikey %}
                <div class="alert alert-danger text-white" role="alert">
                    <strong>Error Getting API Key :</strong> {{ error_message_apikey }}
                </div>
                {% elif error_message_eox_data %}
                <div class="alert alert-danger text-white" role="alert">
                    <strong>Error Getting End Of Support Data ::</strong> {{ error_message_eox_data }}
                </div>
                {% elif eox_data.EOXRecord.0.EOXError %}
                <div class="alert alert-danger text-white" role="alert">
                    <strong>Error Getting End Of Support Data ::</strong> {{ eox_data.EOXRecord.0.EOXError.ErrorID }}, {{ eox_data.EOXRecord.0.EOXError.ErrorDescription }}
                </div>
                {% elif eox_data.EOXError %}
                <div class="alert alert-danger text-white" role="alert">
                    <strong>Error Getting End Of Support Data ::</strong> {{ eox_data.EOXError.ErrorID }}, {{ eox_data.EOXError.ErrorDescription }}
                </div>
                {% else %}
                <h5 class="text-center mb-3">End Of Support Data</h5>
                <div class="table-responsive">
                    <table class="table align-items-center mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th>EOL Product ID</th>
                                <th>Description</th>
                                <th>Bulletin Link</th>
                                <th>LDOS Date</th>
                                <th>Replacement ID</th>
                                <th>Replacement Info</th>
                                <th>Replacement Link</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for record in eox_data.EOXRecord %}
                            <tr>
                                <td>{{ record.EOLProductID }}</td>
                                <td>{{ record.ProductIDDescription }}</td>
                                <td>
                                    {% if record.LinkToProductBulletinURL %}
                                    <a href="{{ record.LinkToProductBulletinURL }}" target="_blank">{{ record.EOLProductID }}</a>
                                    {% else %}
                                    N/A
                                    {% endif %}
                                </td>
                                <td>{{ record.LastDateOfSupport.value }}</td>
                                <td>{{ record.EOXMigrationDetails.MigrationProductId|default:"N/A" }}</td>
                                <td>{{ record.EOXMigrationDetails.MigrationInformation|default:"N/A" }}</td>
                                <td>
                                    {% if record.EOXMigrationDetails.MigrationProductInfoURL %}
                                    <a href="{{ record.EOXMigrationDetails.MigrationProductInfoURL }}"
                                        target="_blank">View</a>
                                    {% else %}
                                    N/A
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}