cisco_softwaresuggestions/urls.py
# myapp/urls.py
from django.urls import path
from .views import get_ss

urlpatterns = [
    path('', get_ss, name='get_ss'),
]

hide1_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
from django.conf.urls import handler500, handler404
from django.shortcuts import render
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('tools-pm/', include('parser_app.urls')),
    path('tools-json/', include('json_editor.urls')),
    path('topology-drawer/', include('topology_drawer.urls')),
    path('tools-cisco/end-of-support/', include('cisco_endofsupport.urls')),
    path('tools-cisco/serial-number-information/', include('cisco_serialnumberinformation.urls')),
    path('tools-cisco/software-suggestions/', include('cisco_softwaresuggestions.urls')),
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('activity-log/', include('activity_log.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

def custom_error_500(request):
    return render(request, '500.html', status=500)

handler500 = custom_error_500

def custom_error_404(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_error_404

parser_app/urls.py
from django.urls import path
from .views import upload_file, download_json

urlpatterns = [
    path("", upload_file, name="upload_file"),
    path('download-json/', download_json, name='download_as_json'),
]

cisco_softwaresuggestions/models.py
from django.db import models

# Create your models here.

cisco_softwaresuggestions/forms.py
# myapp/forms.py
from django import forms

class SerialNumberForm(forms.Form):
    product_id = forms.CharField(label='Product ID', max_length=100)

cisco_softwaresuggestions/views.py
# myapp/views.py
from django.shortcuts import render
from .forms import SerialNumberForm
from .ss import get_apikey, get_ss_data

def get_ss(request):
    api_key = None
    ss_data = None
    error_message_apikey = None
    error_message_ss_data = None

    if request.method == 'POST':
        form = SerialNumberForm(request.POST)
        if form.is_valid():
            product_id = form.cleaned_data['product_id']

            # Call your existing functions to get API key and SS data
            api_key, error_message_apikey = get_apikey()
            if api_key:
                ss_data, error_message_ss_data = get_ss_data(api_key, product_id)

    else:
        form = SerialNumberForm()

    return render(request, 'get_ss.html', {'form': form, 'api_key': api_key, 'ss_data': ss_data,
                                            'error_message_apikey': error_message_apikey,
                                            'error_message_ss_data': error_message_ss_data})

cisco_softwaresuggestions/templates/get_ss.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="row">
    <div class="col-lg-12 mx-auto">
        <div class="card shadow-soft border-radius-lg mb-4">
            <div class="card-header pb-0">
                <a class="h3 d-block mt-3 text-decoration-none text-dark">Get Software Suggestions Data</a>
            </div>
            <div class="card-body form-group">
                <form method="post" action="{% url 'get_ss' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_product_id" class="form-label">Product ID</label>
                        <input type="text" name="product_id" class="form-control border border-light px-3"
                            id="id_product_id" placeholder="Enter Product ID" maxlength="100">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger" id="submit" name="submit">
                            <span class="ni ni-send"></span> Submit
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% if ss_data %}
        <div class="card shadow border-radius-lg mt-4">
            <div class="card-body">
                <div class="mt-4">
                    {% if error_message_apikey %}
                    <div class="alert alert-danger text-white" role="alert">
                        <strong>API Key Error:</strong> {{ error_message_apikey }}
                    </div>
                    {% elif error_message_ss_data %}
                    <div class="alert alert-danger text-white" role="alert">
                        <strong>Data Retrieval Error:</strong> {{ error_message_ss_data }}
                    </div>
                    {% elif ss_data %}
                    <a class="h4 d-block mt-3 text-decoration-none text-danger mt-3 mb-0">Software Suggestions Data</a>

                    <div class="mb-3">
                        <label class="form-label" for="filterSelect">Filter by Suggested or Not:</label>
                        <select id="filterSelect" class="form-select" onchange="filterTable()">
                            <option value="">All</option>
                            <option value="Y">Suggested</option>
                            <option value="N">Not Suggested</option>
                        </select>
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center mb-0" id="myTable">
                            <thead class="bg-light">
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Suggested</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Suggested ID
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">Base
                                        PID</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Software Type
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Release Format
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Release Date
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">Image
                                        Name
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Description
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">Image
                                        Size
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                        Download Link
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for suggestion in ss_data.suggestions %}
                                {% for image in suggestion.images %}
                                <tr>
                                    <td>{{ suggestion.isSuggested }}</td>
                                    <td>{{ suggestion.id }}</td>
                                    <td>{{ suggestion.basePID }}</td>
                                    <td>{{ suggestion.softwareType }}</td>
                                    <td>{{ suggestion.releaseFormat1 }}</td>
                                    <td>{{ suggestion.releaseDate }}</td>
                                    <td>{{ image.imageName }}</td>
                                    <td>{{ image.description }}</td>
                                    {% load custom_filters %}
                                    <td>{{ image.imageSize|format_size }}</td>
                                    <td>
                                        <a href="https://software.cisco.com/download/home/{{ suggestion.mdfId }}"
                                            target="_blank" class="text-danger font-weight-bold">Here</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <script>
                        function filterTable() {
                            var select = document.getElementById("filterSelect");
                            var filter = select.value.toUpperCase();
                            var table = document.getElementById("myTable");
                            var tr = table.getElementsByTagName("tr");

                            for (var i = 1; i < tr.length; i++) {
                                var td = tr[i].getElementsByTagName("td")[0];
                                if (td) {
                                    var txtValue = td.textContent || td.innerText;
                                    tr[i].style.display = (filter === "" || txtValue.toUpperCase() === filter) ? "" : "none";
                                }
                            }
                        }
                    </script>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}